---
name: Docker

'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - README.md
      - compose.yaml
  workflow_dispatch:

concurrency:
  group: Docker/${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
